//PAIS//

CREATE TABLE PAIS (ID_PAIS NUMBER GENERATED ALWAYS AS IDENTITY,
                  NOME VARCHAR2 (30),
                  PRIMARY KEY (ID_PAIS));
                  
//ESTADO//

CREATE TABLE ESTADO (ID_ESTADO NUMBER GENERATED ALWAYS AS IDENTITY,
                  NOME VARCHAR2 (30),
                  PRIMARY KEY (ID_ESTADO));
                  
//CIDADE//

CREATE TABLE CIDADE (CIDADE NUMBER GENERATED ALWAYS AS IDENTITY,
                  NOME VARCHAR2 (30),
                  PRIMARY KEY (ID_CIDADE));
                  
//BAIRRO//

CREATE TABLE BAIRRO (ID_BAIRRO NUMBER GENERATED ALWAYS AS IDENTITY,
                  NOME VARCHAR2 (30),
                  PRIMARY KEY (ID_BAIRRO));                
                  
                
//ENDEREÇO//

CREATE TABLE ENDERECO_CLIENTE (ID_ENDERECO_CLIENTE NUMBER GENERATED ALWAYS AS IDENTITY,
                  NOME VARCHAR2 (30),
                  PRIMARY KEY (ENDERECO_CLIENTE));

ALTER TABLE ESTADO ADD CONSTRAINT FK_ESTADO FOREIGN KEY (ID_PAIS) REFERENCES PAIS;

